### PR TITLE
feature: support view customize

### PR DESCRIPTION
**Pull request by zolunx10**
- config.js中增加 view_theme 参数方便更换自己的view样式 = =
- lib/render.js中增加 partial() 的支持
- 简单修复 /tag/<tag name> 的查看

### CODE REVIEW

**Comment by fengmk2** [comment]
合并了，奇怪为什么许多文件没有怎么更新，却被整个重新覆盖了？

在 2011-11-25，下午8:44， zolunx10 写道：

> - config.js中增加 view_theme 参数方便更换自己的view样式 = =
> - lib/render.js中增加 partial() 的支持
> - 简单修复 /tag/<tag name> 的查看
> 
> You can merge this Pull Request by running:
> 
>  git pull https://github.com/zolunx10/nodeblog view_theme
> 
> Or you can view, comment on it, or merge it online at:
> 
>  https://github.com/fengmk2/nodeblog/pull/3
> 
> -- Commit Summary --
> - update to nodeblog 2.0
> - fix naive tag search for 2.0
> - X10's theme v0.1
> - Merge remote-tracking branch 'upstream/master'
> - Merge branch 'master' into X10
> - \* add support for customizing view (ref views/readme.md)
> 
> -- File Changes --
> 
> M .gitignore (17)
> M README.md (116)
> M app.js (17)
> M config.js.tpl (68)
> M controllers/blog.js (48)
> M controllers/comment.js (110)
> M controllers/post.js (456)
> M controllers/tag.js (39)
> M controllers/user.js (340)
> M db.js (3)
> M history.md (30)
> M lib/cookie.js (116)
> M lib/eventproxy.js (432)
> M lib/render.js (260)
> M lib/session_store.js (168)
> M lib/utils.js (170)
> A public/image/forkme-grey.png (0)
> A public/image/forkme-white.png (0)
> A public/js/modernizr-1.7.min.js (2)
> M public/simple/css/main.css (1616)
> M test/session_store.test.js (124)
> A views/readme.md (33)
> A views/simple/404.html (2)
> M views/simple/archive.html (84)
> M views/simple/index.html (92)
> M views/simple/post/edit.html (92)
> M views/simple/post/item.html (236)
> M views/simple/rss.xml (48)
> M views/simple/user/item.html (58)
> M views/simple/user/login.html (16)
> 
> -- Patch Links --
> 
>  https://github.com/fengmk2/nodeblog/pull/3.patch
>  https://github.com/fengmk2/nodeblog/pull/3.diff
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/fengmk2/nodeblog/pull/3

---

MK2, FaWave, Net4Team
TEL: 18668079069
微博: @Python发烧友
Twitter: @fengmk2
Blog: http://fengmk2.cnblogs.com

**Comment by zolunx10** [comment]
奇怪+1 因为自己这边乱搞了很多branch合并来合并去的, 是不是不小心动到换行符什么的了OTL...

**Comment by fengmk2** [comment]
建议换行符 \n
就可以了

---

Taobao EDP 苏千
Simple is better, MK2

在 2011-11-26，13:38，zolunx10reply@reply.github.com 写到：

**Comment by zolunx10** [comment]
点头, 下次我直接避免覆盖好了这种

以及好奇下, 这个 Show quoted text 引用是怎么打出来的= =

**Pull request merged**
